### ISSUE TITLE
Accidently pushed whole app into "main" branch - how to delete?

### ISSUE THREAD

**Issue by MaerchenfeeimGarten** [flathub/page.codeberg.maerchenfeeimgarten.Pfeilspiel#2]
@hfiguiere How can I delete this branch? The real "main" branch seems to be called "master" containing the flatpak data.

BTW: After cleanup the mess I created: Is it be possible to rename the "master" branch to "main"?

**Comment by hfiguiere** [comment]
>  Is it be possible to rename the "master" branch to "main"?

No it is not.

**Comment by MaerchenfeeimGarten** [comment]
OK.

**Comment by MaerchenfeeimGarten** [comment]
@hfiguiere How remove the main branch containing the whole source code of Pfeilspiel TNG?

I have accidently added the remote for this repo to the wrong local git repo and pushed to main.
Now the source code of the app is in here and if I try to clean up and delete the main branch, there is an error message that it is protected...

**Comment by hfiguiere** [comment]
deleted now.

**Comment by MaerchenfeeimGarten** [comment]
@hfiguiere Thank you very much.
